### ISSUE TITLE
Zoom option

### ISSUE THREAD

**Issue by NavidK0** [MieleMadness/Tinypage#20]
Should implement

```css
.zoom {
    zoom: 2;
    -moz-transform: scale(2);
    -moz-transform-origin: 0 0;
}
```

Needs testing. May not go into final product.
