### ISSUE TITLE
Add ability for cover photo alongside avatar

### ISSUE THREAD

**Issue by NavidK0** [MieleMadness/Tinypage#6]
```css
img.nc-avatar {
border: solid 2px #FFF; /* Your Avatar border width & color /
box-shadow: 0 2px 5px rgba(0,0,0,.25);
width: 120px !important;
height: 120px !important;
margin-top: min(calc(56.25vw - 65px) , 180px);
}
body, html {
background-size: cover;
background-position: center;
background-repeat: no-repeat;
background: #000; / Placeholder BG Color if image doesn't load /
background-image: url('');
overflow-x: hidden !important;
position:relative;
z-index: -2;
}

.sl-banner {
background: red;
position:absolute;
top:0;
left:0;
right:0;
padding-bottom: min(56.25%,240px);
width: 100%;
max-width: 416px;
border-radius: 10px 10px 3px 3px;
background: #9D50BB; / Your cover background color, fallback if image doesn't load/before image loads /
background: url('https://i.imgur.com/KM7HbTC.png%27);
background-size: cover;
background-position: center;
margin: 10px auto;
z-index:-1;
}

section {margin-top: 10px;}

.sl-bg {
background: transparent !important; / DO NOT CHANGE /
}

@media(max-width:400px) {
section {margin-top: 0px;}
.sl-banner {
border-radius: 0 0 3px 3px;
margin: 0 auto;
}
}

section {
padding-top: 0 !important;
}
/ DO NOT REMOVE /
/ Added by Tinypage Staff /
.sl-headline {
    background-image: url("data:image/svg+xml,%3Csvg width='404' height='404' viewBox='0 0 404 404' fill='none' xmlns='http://www.w3.org/2000/svg%27%3E%3Ccircle cx='202' cy='202' r='182' fill='%2316A3F2' stroke='white' stroke-width='40'/%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M189.028 300.336L291.11 123.524L253.83 102L175.373 236.663L138.482 198.701L113 224.182L188.797 301.024L189.028 300.336Z' fill='white'/%3E%3C/svg%3E%0A");
    background-size: 18px;
    background-position: right center;
    padding-right: calc(18px + .5em);
    background-repeat: no-repeat;
}
/ End staff edits */
```
